### ISSUE TITLE
Large mounting plate threads are misformed

### ISSUE THREAD

**Issue by Arkanoid0** [KinkyMakers/OSSM-hardware#15]
the large mounting plate option (Hardware/OSSM Printed Parts/end effector options/24mm threaded/Vampix 24mm Tie Down and Suction Plate - LARGE.stl) has misinformed threads as designed, the threads end before exiting the boss preventing the screw from threading.

**Comment by ortlof** [comment]
Hi Thanks. Fixed it Uploads will be done in the next days.

**Comment by greatpirategalaxy** [comment]
Version 2 files added to the repository.
