### ISSUE TITLE
Electronics Board V2.1 won't store WiFi credentials

### ISSUE THREAD

**Issue by moarkaboom** [KinkyMakers/OSSM-hardware#26]
After accessing the wifi setup page, I connect to my wifi and enter the credentials. The OSSM reboots and I can see it come online very briefly on my router, but as soon as it's done booting, it disappears from my network. 
When I reboot and connect to the wifi setup page again, it says "No AP set" even though I configured it. 
I cant seem to get it to store the credentials and stay connected to my network.

**Comment by greatpirategalaxy** [comment]
Addressed on Discord
